### ISSUE TITLE
Script occasionally fails to load an MRA

### ISSUE THREAD

**Issue by Mellified** [mrchrisster/mister-arcade-attract#4]
After updating mra.txt with all currently available mra files for all cores the script occasionally fails to load. This may be the result of special characters in the file names, or something else entirely. While finding the underlying issue is best, it is possible to harden the script by adding verification and retry logic:
`until [ -f "/media/fat/_arcade/${mra}" ]; do mra=$(shuf -n 1 /media/fat/Scripts/mra.txt); done`

This could be included after each `mra=$(shuf -n 1 /media/fat/Scripts/mra.txt); done` statement in the script to ensure the mra loaded is in fact a valid file on the filesystem.

**Comment by mrchrisster** [comment]
Thanks. I did indeed run into issues with certain cores because of special characters. I like your idea about the update script but for my purpose I only wanted horizontal games to be displayed.
