### ISSUE TITLE
Loop missing inside sleepfpga()

### ISSUE THREAD

**Issue by Mellified** [mrchrisster/mister-arcade-attract#5]
The latest version of the ArcadeAttractMode-On.sh script uses a new method to switch cores without a reboot - fantastic! However, the new call no longer loops itself. As a result the script loads an arcade core, switches once, and never switch again - because sleepfpga() has exited.

To resolve this I suggest wrapping the commands inside sleepfpga() with a loop:
```
sleepfpga()
{
    while [ true ]; do
    	sleep 300
    	mra=$(shuf -n 1 /media/fat/Scripts/mra.txt)
    	until [ -f "/media/fat/_Arcade/${mra}" ]; do mra=$(shuf -n 1 /media/fat/Scripts/mra.txt); done
    	echo "load_core /media/fat/_Arcade/${mra}" > /dev/MiSTer_cmd
    done
}
```

**Comment by mrchrisster** [comment]
I like your suggestions! I didn't have time to test the new method without reboot properly, so please feel free to make the necessary changes. Just sent you a collaborator invite

**Comment by Mellified** [comment]
I ended up finding a bunch of other issues with the direct loading method. The most significant is corruption of video output after loading several cores. I reworked things to use the new method 3 times then the old way. Submitted this in a PR for your review.

**Comment by Mellified** [comment]
Resolved.

**Comment by mrchrisster** [comment]
maybe it's best to switch back to the old method, what do you think?

**Comment by Mellified** [comment]
I thought about that too. Skipping the reboot wait time and the 10 second timeout on the menu is really nice with the new method though.

The corruption issue is a known problem loading multiple cores without a reset. It may get fixed eventually.

Maybe it is better to have this script work the same way every load though?

**Comment by mrchrisster** [comment]
Seems like this could be fixed down the road so why don't we leave it like you implemented it for now. Let's revisit down the road and see if we can get rid of the reboot. Definitely looks a lot cleaner not having the menu show up in between core bootups.

**Comment by Mellified** [comment]
I'm testing an actual Linux reboot command in place of running `fpga /media/fat/menu.rbf` periodically. I am still seeing a lot of black screen / no OSD arcade core loads with the current design.

The script does recover, but two minutes of a black screen isn't very _attract-ive_.

**Comment by mrchrisster** [comment]
Ha, nice pun there! That's the beauty of the curated list. I weeded out all the cores that caused issues for my setup. In my case I also use a S-video converter which causes color problems with some cores.

**Comment by Mellified** [comment]
“Reboot now” was suggested as a way to reset the system. When I tried it the result was it loading back into the same core. 

Another possibility suggested is “kill and then restart using  ./media/fat/MiSTer avoids restarting linux”. Would be “killall MiSTer” I expect.

**Comment by mrchrisster** [comment]
Problem seemed to be related to certain cores, no issues with curated horizontal list after some testing.
